In [1]:
import pandas as pd
import numpy as np
from scipy import stats

# 1. Cutlets (2-Sample test)

In [2]:
df = pd.read_csv("C:/Users/USER/Desktop/Excelr/Data Science/Assignment/Assignment 3 Hypothesis Testing/Cutlets.csv")
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [3]:
df.mean()

Unit A    7.019091
Unit B    6.964297
dtype: float64

In [4]:
stats.ttest_ind(df.iloc[:,0],df.iloc[:,1])

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.47223947245995)

# 2. LabTaT (ANOVA test)

In [5]:
df1 = pd.read_csv("C:/Users/USER/Desktop/Excelr/Data Science/Assignment/Assignment 3 Hypothesis Testing/LabTAT.csv")
df1

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [6]:
df1.mean()

Laboratory 1    178.361583
Laboratory 2    178.902917
Laboratory 3    199.913250
Laboratory 4    163.682750
dtype: float64

In [7]:
stats.f_oneway(df1.iloc[:,0],df1.iloc[:,1],df1.iloc[:,2],df1.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

# 3. BuyerRatio (Chi-square test)

In [8]:
df2 = pd.read_csv("C:/Users/USER/Desktop/Excelr/Data Science/Assignment/Assignment 3 Hypothesis Testing/BuyerRatio.csv")
df2

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [9]:
df2_n = df2[['East','West','North','South']]
df2_n

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [10]:
Observed_Values = df2_n.values
print('Observed_Values- \n',Observed_Values)

Observed_Values- 
 [[  50  142  131   70]
 [ 435 1523 1356  750]]


In [11]:
Expected_Values = stats.chi2_contingency(df2_n)
Expected_Values

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [12]:
Expected_Values1=Expected_Values[3]
Expected_Values1

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [13]:
from scipy.stats import chi2
chi_square=sum([(Observed_Values-Expected_Values1)**2/Expected_Values1])
chi_square

array([[1.22390537e+00, 1.57777715e-01, 1.05418400e-04, 7.34330980e-02],
       [1.18355022e-01, 1.52575399e-02, 1.01942498e-05, 7.10118295e-03]])

In [14]:
chi_square1=sum(chi_square)
chi_square1

array([1.34226039e+00, 1.73035255e-01, 1.15612650e-04, 8.05342809e-02])

## OR

In [15]:
chi_square_statistics=chi_square[0]+chi_square[1]
print('chi_square_statistics',chi_square_statistics)

chi_square_statistics [1.34226039e+00 1.73035255e-01 1.15612650e-04 8.05342809e-02]


In [16]:
chi_square_statistics=sum(chi_square1)
print('chi_square_statistics',chi_square_statistics)

chi_square_statistics 1.5959455386610577


In [17]:
no_of_rows=len(df2_n.iloc[0:2,0])
no_of_col=len(df2_n.iloc[0,0:4])
dof=(no_of_rows-1)*(no_of_col-1)
dof

3

In [18]:
P_value=1-chi2.cdf(chi_square_statistics, dof)
print('P_value=',P_value)

P_value= 0.6603094907091882


# 4. Costomer+OrderForm (chi-square test)

In [19]:
df4= pd.read_csv('C:/Users/USER/Desktop/Excelr/Data Science/Assignment/Assignment 3 Hypothesis Testing/Costomer+OrderForm.csv')

In [20]:
df4

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [21]:
pd.get_dummies(df4)

Phillippines_Defective  Phillippines_Error Free  Indonesia_Defective  \
0                         0                        1                    0   
1                         0                        1                    0   
2                         0                        1                    1   
3                         0                        1                    0   
4                         0                        1                    0   
..                      ...                      ...                  ...   
295                       0                        1                    0   
296                       0                        1                    0   
297                       0                        1                    0   
298                       0                        1                    0   
299                       0                        1                    1   

     Indonesia_Error Free  Malta_Defective  Malta_Error Free  India_Defective  \
0                       1                1                 0                0   
1                       1                0                 1                1   
2                       0                1                 0                0   
3                       1                0                 1                0   
4                       1                1                 0                0   
..                    ...              ...               ...              ...   
295                     1                0                 1                0   
296                     1                0                 1                0   
297                     1                1                 0                0   
298                     1                0                 1                0   
299                     0                1                 0                0   

     India_Error Free  
0                   1  
1                   0  
2                   1  
3                   1  
4                   1  
..                ...  
295                 1  
296                 1  
297                 1  
298                 1  
299                 1  

[300 rows x 8 columns]

In [22]:
df5=df4.Phillippines.value_counts(),df4.Indonesia.value_counts(),df4.Malta.value_counts(), df4.India.value_counts()
df5

(Error Free    271
 Defective      29
 Name: Phillippines, dtype: int64,
 Error Free    267
 Defective      33
 Name: Indonesia, dtype: int64,
 Error Free    269
 Defective      31
 Name: Malta, dtype: int64,
 Error Free    280
 Defective      20
 Name: India, dtype: int64)

In [23]:
df6=pd.DataFrame({'Phillippines':[271,29],'Indonesia':[267,33],'Malta':[269,31],'India':[280,20]})
df6

Phillippines  Indonesia  Malta  India
0           271        267    269    280
1            29         33     31     20

In [24]:
row = df6['Phillippines'].count()
col = len(df6.columns)
dof4 = (row-1)*(col-1)
dof4

3

In [25]:
o = df6.values
print('observed_values- \n',o)

observed_values- 
 [[271 267 269 280]
 [ 29  33  31  20]]


In [26]:
from scipy.stats import chi2
Expected_Values=stats.chi2_contingency(df6)
print('Expected_Values- \n', Expected_Values)

Expected_Values- 
 (3.858960685820355, 0.2771020991233135, 3, array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]]))


In [27]:
e=Expected_Values[3]
e

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [28]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e])
chi_square

array([[2.06991720e-03, 8.30266789e-02, 2.78288868e-02, 2.50459982e-01],
       [1.99115044e-02, 7.98672566e-01, 2.67699115e-01, 2.40929204e+00]])

In [29]:
chi_square_statistics=sum(chi_square)
print('chi_square_statistics',chi_square_statistics)

chi_square_statistics [0.02198142 0.88169925 0.295528   2.65975202]


In [30]:
chi_final=sum(chi_square_statistics)
chi_final

3.8589606858203545

In [31]:
P_value4=1-chi2.cdf(chi_final, dof4)
print('P_value4=',P_value4)

P_value4= 0.2771020991233144


# 5. Fantaloons (2-proportion test)

In [32]:
df4= pd.read_csv('C:/Users/USER/Desktop/Excelr/Data Science/Assignment/Assignment 3 Hypothesis Testing/Faltoons.csv')
df4

Weekdays Weekend
0       Male  Female
1     Female    Male
2     Female    Male
3       Male  Female
4     Female  Female
..       ...     ...
395   Female    Male
396   Female  Female
397   Female  Female
398   Female    Male
399   Female  Female

[400 rows x 2 columns]

In [33]:
df4_replace= df4.replace(("Male","Female"),(0,1))
df4_replace

Weekdays  Weekend
0           0        1
1           1        0
2           1        0
3           0        1
4           1        1
..        ...      ...
395         1        0
396         1        1
397         1        1
398         1        0
399         1        1

[400 rows x 2 columns]

In [34]:
a = df4_replace.Weekdays.values
a

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,

In [35]:
b = df4_replace.Weekend.values
b

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,

In [36]:
a.mean(), b.mean()

(0.7175, 0.5825)

In [37]:
import statsmodels.api as sm
sm.stats.ttest_ind(a,b)

(4.038383581687956, 5.901387942852848e-05, 798.0)